### ISSUE TITLE
How to use it with Behat?

### ISSUE THREAD

**Issue by claudiu-cristea** [minkphp/webdriver-classic-driver#28]
Currently, my behat.yml includes these settings:

```yaml
  extensions:
    Drupal\MinkExtension:
      base_url: ${env.DRUPAL_BASE_URL}
      ajax_timeout: 10
      files_path: ${joinup.dir}/tests/fixtures/files
      browserkit_http:
        guzzle_request_options:
          verify: false
      javascript_session: selenium2
      browser_name: ${behat.browser_name}
      selenium2:
        wd_host: ${behat.selenium.webdriver_url}
        capabilities:
          browser: chrome
          nativeEvents: true
          marionette: true
          browserName: chrome
          version: '*'
          extra_capabilities:
            loggingPrefs:
              performance: ALL
              browser: ALL
            chromeOptions:
              w3c: false
              args:
                - '--no-sandbox'
                - '--start-maximized'
                - '--disable-gpu'
                - '--window-size=1600,1200'
                - '--disable-dev-shm-usage'
                - '--disable-setuid-sandbox'
                - '--disable-web-security'
                - '--DNS-prefetch-disable'
                - '--disable-translate'
                - '--ignore-certificate-errors'
                - '--test-type'
                - '--disable-extensions'
                - '--incognito'
                - '--disable-infobars'
                - '--allowed-ips=*'
                - '--whitelisted-ips=*'
```

What should I do to use this driver?

Note: Drupal\MinkExtension is https://github.com/jhedstrom/drupalextension
