### ISSUE TITLE
Possibly reduce build matrix size

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#40]
### Current state

Right now the test matrix looks like this:

1. test `each web browser` (firefox & chrome) x `every PHP version` (7.4, 8.0, 8.1, 8.2) x `every selenium server version` (2, 3, 4) = 24 builds
4. test rarely used web browsers, like chromium and edge = 2 builds

Total: **26 builds**.

### Proposition

If we assume, that the driver doesn't have any browser-specific IFs, then we should:

1. test `each web browser` x `each selenium version` on the latest PHP version = 6 builds
3. test `single browser` x `latest selenium version` on every PHP version = 4 builds
4. test rarely used web browsers, like chromium and edge as now = 2 builds

Total: **12 builds**.

Does this make sense or am I missing something?

**Comment by uuf6429** [comment]
I don't like the current matrix size either, especially considering it runs twice - for each commit pushed and for the PR itself. Maybe we should just go for `push`?
https://github.com/minkphp/webdriver-classic-driver/blob/main/.github/workflows/ci.yml#L4

**Comment by uuf6429** [comment]
As I understand the [GitHub documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#about-matrix-strategies), to do what you propose we would need to define which case goes into the matrix and the rest of the cases defined manually (like the "rare browsers" case).

OR we define a matrix of everything and the exclude individually. Probably the first case would be the best.

Something like:
```yaml
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.3' ]
        browser: [ 'firefox', 'chrome' ]
        selenium: [ '2.53.1', '3', '4' ]
        include:
          # Check on different PHP versions
          - php: '7.4'
            browser: 'chrome'
            selenium: '4'
          - php: '8.0'
            browser: 'chrome'
            selenium: '4'
          - php: '8.1'
            browser: 'chrome'
            selenium: '4'
          - php: '8.2'
            browser: 'chrome'
            selenium: '4'
          - php: '8.3'
            browser: 'chrome'
            selenium: '4'
          # Check on less-common browsers
          - php: '8.3'
            browser: 'edge'
            selenium: '4'
          - php: '8.3'
            browser: 'chromium'
            selenium: '4'
      fail-fast: false
```
