### ISSUE TITLE
Using CodeCov Flags to separate tests by Browser+Selenum_version

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#62]
What CodeCov flags are: https://docs.codecov.com/docs/flags

That should separate flaky tests depending on a browser+selenium version combo.

Example code (the `flags: ...` line added) taken from https://docs.codecov.com/docs/github-5b-setting-coverage-standards-with-flags:

```yaml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        # See https://nektosact.com/usage/index.html#skipping-steps
        if: ${{ !env.ACT && !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: ${{ matrix.browser }}:${{ matrix.selenium }}
```
